// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const storeNewRefreshTokenInfo = `-- name: StoreNewRefreshTokenInfo :exec
INSERT INTO refresh_tokens(token, created_at, updated_at, user_id, expires_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3
)
`

type StoreNewRefreshTokenInfoParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreNewRefreshTokenInfo(ctx context.Context, arg StoreNewRefreshTokenInfoParams) error {
	_, err := q.db.ExecContext(ctx, storeNewRefreshTokenInfo, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const updateRevokedAt = `-- name: UpdateRevokedAt :exec
UPDATE refresh_tokens
SET revoked_at = $1, updated_at = $2
WHERE token = $3
`

type UpdateRevokedAtParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) UpdateRevokedAt(ctx context.Context, arg UpdateRevokedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateRevokedAt, arg.RevokedAt, arg.UpdatedAt, arg.Token)
	return err
}
